import type { Metadata } from "next";
import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import { dark } from "@clerk/themes"
import {ThemeProvider} from "@/components/components/theme-provider";
import {ReactNode} from "react";
import {Toaster} from "sonner";


const arimo = Arimo({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-arimo',
})
const chivo = Chivo({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-chivo',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
      <ClerkProvider
        appearance={{
            baseTheme: dark,
        }}
      >
        <html lang="en">
              <body className={arimo.variable + ' ' + chivo.variable}>
                  <ThemeProvider
                      attribute="class"
                      forcedTheme="light"
                      storageKey="gamehub-theme"
                  >
                      <Toaster
                        theme="light"
                        position='bottom-center'
                      />
                      {children}
                  </ThemeProvider>
              </body>
        </html>
      </ClerkProvider>
  );
}
